### ISSUE TITLE
duplicate recipes for routing and annotations

### ISSUE THREAD

**Issue by jrushlow** [symfony/recipes#1030]
the `doctrine/annotations` recipe creates a `config/routes/annotations.yaml` that contains 

```yaml
controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
```

https://github.com/symfony/recipes/blob/master/doctrine/annotations/1.0/config/routes/annotations.yaml

&&

the `symfony/router` recipe creates `config/routes.yaml` that contains 

```yaml
controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
```

https://github.com/symfony/recipes/blob/master/symfony/routing/6.0/config/routes.yaml

Which recipe can we remove?
