### ISSUE TITLE
Want to add routes from route.yaml or route folder in swagger documentation. Is there any way of it?

### ISSUE THREAD

**Issue by asifmuztaba1** [symfony/recipes#1127]
Hi, I am using api-platform to create an api. I have setup jwt login system and my login url is `api/login` which takes post requests. 
This `api/login` route is registered in routes/api_platform.yaml 
```
api_platform:
    resource: .
    type: api_platform
    prefix: /api
login:
    path: /api/login
    methods: ['POST']
api_doc:
    path: /api-doc
    controller: api_platform.swagger.action.ui
```
   but this `api/login` route is not documented in swagger.
   
   i am also curious to know the function of routes/api_platform.yaml and what is the meaning of `resource: .(dot) `  ? what else argument are available there without (dot) ?
