### ISSUE TITLE
enhancement: Enable the collection of backtrace for each doctrine query by default

### ISSUE THREAD

**Issue by Crovitche-1623** [symfony/recipes#1190]
The following configuration brings up a useful menu for debugging using the profiler in dev environment:

```yaml
when@dev:
    doctrine:
        dbal:
            connections:
                default:
                    profiling_collect_backtrace: true
```

<img width="954" alt="image" src="https://user-images.githubusercontent.com/35468476/233700126-9928a499-dfcb-4048-b8b5-708e204048d9.png">

Wouldn't it be a good idea to enable this by default ?
