### ISSUE TITLE
mercure_1  | Error: reading config from file: open /etc/caddy/Caddyfile.dev: no such file or directory

### ISSUE THREAD

**Issue by genesis59** [symfony/recipes#1327]
Hello,
I have found an error in the Mercury Bundle recipe for Symfony. Here are the details:
### Error Description
When I run the command `docker-compose up`, I get the following error:
mercure_1  | Error: reading config from file: open /etc/caddy/Caddyfile.dev: no such file or directory

### Proposed Fix
Update the Docker configuration as follows:

```yaml
### replace this line
 command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
### by
 command: /usr/bin/caddy run --config /etc/caddy/Caddyfile
```
Thank you for your attention and for all the work you do!
