### ISSUE TITLE
Security: Entity provider key not found

### ISSUE THREAD

**Issue by Guikingone** [symfony/recipes#153]
Hi, I try to use Guard inside a Flex project and the entity provider tells me that the key couldn't be found inside the security.file, I've checked many times the syntax but the error stays the same : 

![error](https://img4.hostingpics.net/pics/831973Capturedecran20170815a131330.png)

Here's the security.yml file : 

```yaml
security:
    encoders:
        App\Model\User:
            algorithm: bcrypt

    providers:
        api_entity_provider:
            entity:
                class: App\Model\User
                property: apiToken

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: null

        api:
            anonymous: ~
            logout: ~
            provider: api_provider
            guard:
                authenticators:
                    - App\Guard\ApiTokenAuthenticator
```

Note: The error only appear using Flex, I've a classic Sf project along this one on the last version and this last one work.
