### ISSUE TITLE
[WebServerBundle] Add config for using the server log

### ISSUE THREAD

**Issue by maidmaid** [symfony/recipes#263]
If you want launch `server:log`, you need this config:

```yml
monolog:
    handlers:
        server_log:
            type: server_log
            host: 0:9911
```

Would it be interesting to add this dev config to WebServerBundle recipe?
