### ISSUE TITLE
[Question] Why use relative paths instead of kernel.project_dir?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/recipes#362]
This question was asked by @LPodolski in https://github.com/symfony/symfony-docs/issues/8373.

For example, in this recipe:

https://github.com/symfony/recipes/blob/938ca8419df7e90a92dfb12f4e5357f1a81fa63a/symfony/framework-bundle/3.3/config/services.yaml#L16-L18

Why use that instead of the following?

```yaml
    App\:
        resource: '%kernel.project_dir%/src/*'
        exclude: '%kernel.project_dir%/src/{Entity,Migrations,Tests,Kernel.php}'
```
