### ISSUE TITLE
Log PHP warnings in prod

### ISSUE THREAD

**Issue by maidmaid** [symfony/recipes#528]
The prod env doesn't log the PHP warnings like when [we pass an uncountable thing to the count() function](  http://php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types).
https://github.com/symfony/recipes/blob/481ce0a9f1619c0bea95d1b37c4477a9880f7039/symfony/monolog-bundle/3.1/config/packages/prod/monolog.yaml#L24
It could be better to change info to warning here.

**Comment by B-Galati** [comment]
I think it would be the crossed finger handler line to change instead:

https://github.com/symfony/recipes/blob/481ce0a9f1619c0bea95d1b37c4477a9880f7039/symfony/monolog-bundle/3.1/config/packages/prod/monolog.yaml#L5

**Comment by maidmaid** [comment]
I would prefer to keep the main handler for critical errors. What about :
```yaml
monolog:
    handlers:
        warning:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.warning.log"
        warning_filter:
            type: filter
            handler: warning
            min_level: warning
            max_level: warning
            channels: ["php"]
```
