### ISSUE TITLE
"App" logs separated

### ISSUE THREAD

**Issue by maidmaid** [symfony/recipes#533]
The "app" logs like

> new bill paid

should be separated in a dedicated log file by default IMO.

They are business logs, and there are currently in the main file logs among all the others. Moreover, in prod env, "app" logs with info level shoudn't be ignored like now.

```yml
// config/packages/monolog.yaml
monolog:
    handlers:
        app:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.app.log"
            level: debug
            channels: ["app"]
```
