### ISSUE TITLE
Framework bundle Kernel: consider the order config files are loaded (security misconfiguration)

### ISSUE THREAD

**Issue by glynnforrest** [symfony/recipes#829]
As far as I understand it, the security bundle doesn't allow for firewalls to be defined in multiple files - see https://github.com/symfony/symfony/issues/25021, https://github.com/symfony/symfony/issues/22308, https://github.com/symfony/symfony/issues/24461.

When multiple security config files are loaded, an exception should be thrown: ***You are not allowed to define new elements for path "security.firewalls". Please define all elements for this path in one config file.***

However, depending on the order config files are loaded in `Kernel::configureContainer()`, this process can fail silently and change the security config.

With these config files:

```yaml
# config/packages/security.yaml
security:
    firewalls:
        main:
            # ...
            remember_me:
                secure: true
            # ...

    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: false
    # ...
```

```yaml
# config/packages/dev/security.yaml
security:
    firewalls:
        main:
            remember_me:
                secure: false
```

and this loading order in `Kernel::configureContainer()` (the recipe default):

```php
protected function configureContainer(ContainerBuilder $container, LoaderInterface $loader)
{
    // ...

    $loader->load($confDir . '/{packages}/*' . self::CONFIG_EXTS, 'glob');
    $loader->load($confDir . '/{packages}/' . $this->environment . '/*' . self::CONFIG_EXTS, 'glob');

    // ...
}
```

There is no error thrown when the container loads. The config of `access_decision_manager` is now different between environments:

```bash
./bin/console deb:conf security access_decision_manager.strategy
# affirmative

APP_ENV=prod ./bin/console deb:conf security access_decision_manager.strategy
# unanimous
```

Both environments should be `unanimous`.

Changing the order of the config file loading does show an error however:

```php
$loader->load($confDir . '/{packages}/' . $this->environment . '/*' . self::CONFIG_EXTS, 'glob');
$loader->load($confDir . '/{packages}/*' . self::CONFIG_EXTS, 'glob');
```

Is it possible to change the order of these lines in the recipe, or would it break other things?
